project:
  type: website
  output-dir: docs

website:
  title: "Wellness Meets Data"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/praj0022
format:
  html:
    theme: cosmos
    css: styles.css



